# Generated by Django 6.0.4 on 2026-08-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shop_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_all',
            name='image',
            field=models.ImageField(upload_to='shop_images/'),
        ),
    ]
