# Generated by Django 6.0.4 on 2026-08-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shop_all_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_collection',
            name='category',
            field=models.CharField(choices=[('watches', 'Watches'), ('bracelets', 'Bracelets'), ('smart-access', 'Smart Access'), ('combat', 'Combat')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home_collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='home_collection',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
