# Generated by Django 6.0.4 on 2026-08-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_home_collection_category_home_collection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_all',
            name='category',
            field=models.CharField(choices=[('watches', 'Watches'), ('bracelets', 'Bracelets'), ('smart-access', 'Smart Access'), ('combat', 'Combat')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_all',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop_all',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shop_all',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
