# Generated by Django 6.0.4 on 2026-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_collection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
