# Generated by Django 6.0.4 on 2026-08-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_home_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_collection',
            name='slug',
        ),
    ]
