# Generated by Django 6.0.4 on 2026-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_home_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_all',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
