# Generated by Django 6.0.4 on 2026-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shop_all_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_all',
            name='slug',
        ),
        migrations.AlterField(
            model_name='home_collection',
            name='category',
            field=models.CharField(choices=[('watches', 'Watches'), ('bracelets', 'Bracelets'), ('smart-access', 'Smart Access'), ('combo', 'Combo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shop_all',
            name='category',
            field=models.CharField(choices=[('watches', 'Watches'), ('bracelets', 'Bracelets'), ('smart-access', 'Smart Access'), ('combo', 'Combo')], max_length=50),
        ),
    ]
