# Generated by Django 6.0.4 on 2026-08-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_shop_all_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_all',
            name='category',
            field=models.CharField(choices=[('watches', 'Watches'), ('bracelets', 'Bracelets'), ('smart-accessories', 'Smart Accessories'), ('combo', 'Combo')], max_length=50),
        ),
    ]
