# Generated by Django 6.0.4 on 2026-08-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_clientreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
