# Generated by Django 6.0.4 on 2026-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_clientreview_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_all',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
