# Generated by Django 6.0.4 on 2026-08-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_shop_all_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
