# Generated by Django 6.0.4 on 2026-08-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
