# Generated by Django 6.0.4 on 2026-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('Order Question', 'Order Question'), ('Product Inquiry', 'Product Inquiry'), ('Feedback', 'Feedback'), ('Other', 'Other')], max_length=100),
        ),
    ]
