# Generated by Django 6.0.4 on 2026-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_delivery_address_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', '💳 Paystack (Card)'), ('flutterwave', '🌍 Flutterwave'), ('whatsapp', '💬 WhatsApp / Bank Transfer'), ('manual', '💰 Manual / Cash')], default='whatsapp', max_length=20),
        ),
    ]
