# Generated by Django 6.0.4 on 2026-09-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
    ]
